version: '3.4'

services:
  express:
    image: type-script-base
    container_name: type-script-base-01
    build: .
    volumes: 
      - $PWD/log/:/usr/src/app/log/
      - $PWD/uploads/:/usr/src/app/uploads/
    ports:
      - 8000:8000